### ISSUE TITLE
INVALID_ENUM_VALUE error – Is it possible to deploy a cluster M0 with AWS CDK?

### ISSUE THREAD

**Issue by ilyagru** [mongodb/mongodbatlas-cloudformation-resources#608]
Hi! I'm having issues deploying a sample Atlas Basic stack when using the M0 instance size. As far as I understand, both `M0` and `EU_CENTRAL_1` should be supported as per [MongoDB docs](https://www.mongodb.com/docs/atlas/reference/amazon-aws/#std-label-amazon-aws).

Could you please help me out? I'm looking a way to deploy/play/test an AWS CDK stack with a free MongoDB tier. Is there eventually a different way to test such an AWS CDK deployment of MongoDB with free tier?

### CDK Template 

```ts
# Copy-paste your templates info here

new AtlasBasic(this, 'AtlasBasic', {
  clusterProps: {
    name: `test-cluster`,
    replicationSpecs: [
      {
        numShards: 1,
        advancedRegionConfigs: [
          {
            analyticsSpecs: {
              ebsVolumeType: 'STANDARD',
              instanceSize: 'M0',
              nodeCount: 1
            },
            electableSpecs: {
              ebsVolumeType: 'STANDARD',
              instanceSize: 'M0',
              nodeCount: 1
            },
            priority: 7,
            regionName: 'EU_CENTRAL_1'
          }
        ]
      }
    ]
  },
  projectProps: {
    orgId: process.env.MONGODB_ORGANIZATION_ID
  },
  ipAccessListProps: {
    accessList: [
      {
        ipAddress: process.env.MONGODB_CURRENT_IP,
        comment: 'My current IP address'
      }
    ]
  },
  profile: process.env.CDK_DEPLOY_PROFILE
})
```

### Steps to Reproduce

1. Create a sample AWS CDK app.
2. Use `atlas-basic` example.
3. Change `instanceSize` to `M0`.
4. `cdk deploy`.

### Expected Behavior

The stack is deployed successfully.

### Actual Behavior

The stack fails to deploy and returns an error `INVALID_ENUM_VALUE`.
```
Error: The stack named <> failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "POST https://cloud.mongodb.com/api/atlas/v1.5/groups/<>/clusters: 400 (request "INVALID_ENUM_VALUE") An invalid enumeration value M0 was specified." (RequestToken: <>, HandlerErrorCode: InvalidRequest)
```

**Comment by colm-quinn** [comment]
hi @ilyagru,
We're currently aware of the limitation with deploying shared tier clusters with CFN & CDK. While we add support, you can only deploy M10+ with CFN/CDK.

For internal tracking [INTMDB-905](https://jira.mongodb.org/browse/INTMDB-905) wioll add the required support here & is currently being investigated.

**Comment by andreaangiolillo** [comment]
Hello @ilyagru,

We have released the fix. Make sure to use the latest version of the cluster CFN resource and to use cdk [v1.0.2](https://constructs.dev/packages/awscdk-resources-mongodbatlas/v/1.0.2?lang=java). Here is an example of how to deploy an M0 cluster: [free-tier-M0-cluster.json](https://github.com/mongodb/mongodbatlas-cloudformation-resources/blob/master/examples/cluster/free-tier-M0-cluster.json).

Thanks!

**Comment by ilyagru** [comment]
Amazing @andreaangiolillo! Thank you very much!

**Comment by ebenedetti-futuring** [comment]
Hi for me the issue still persists:

`
      const atlasBasic = new AtlasBasic(this, 'AtlasBasic', {
        clusterProps: {
          name: 'Cluster0',
          clusterType: 'REPLICASET',
          replicationSpecs: [
            {
              numShards: 1,
              advancedRegionConfigs: [
                {
                  analyticsSpecs: {
                    ebsVolumeType: "STANDARD",
                    instanceSize: "M0",
                    nodeCount: 1
                  },
                  electableSpecs: {
                    ebsVolumeType: "STANDARD",
                    instanceSize: "M0",
                    nodeCount: 3
                  },
                  priority: 7,
                  regionName: "EU_NORTH_1",
                  providerName: "AWS",
                  backingProviderName: "AWS"
                }]
            }]
        },
        projectProps: {
          name: 'demo',
          orgId: '<myorgid>', //Static
        },
        ipAccessListProps: {
          accessList: [
            {ipAddress: '0.0.0.0', comment: 'All'}
          ]
        },
        profile: 'default',
      });
`
AtlasBasic/cluster-AtlasBasic () Resource handler returned message: "https
://cloud.mongodb.com/api/atlas/v2/groups/<groupid>/clusters POST: HTTP 400 Bad Request (Error code: "INVALID_ENUM_VALUE") Detail: An invalid enumeration value M0 was specified. Reason: Bad Request. Params: [M0]" (R
equestToken: <request_token>, HandlerErrorCode: InvalidRequest)
